# Generated by Django 4.0.3 on 2022-04-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.EmailField(max_length=50, verbose_name='Nombre')),
                ('staff_lastname', models.EmailField(max_length=50, verbose_name='Apellido')),
                ('birth', models.DateField(verbose_name='Fecha Nacimiento')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('rol', models.CharField(choices=[('0', 'TECNICO'), ('1', 'MEDICO'), ('2', 'PREPARADOR')], max_length=1, verbose_name='Rol')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
