# Generated by Django 4.0.3 on 2022-04-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50, verbose_name='Name')),
                ('player_lastname', models.EmailField(max_length=50, verbose_name='Lastname')),
                ('birth', models.DateField(verbose_name='Birth')),
                ('team_position', models.CharField(choices=[('0', 'DEFENSA CENTRAL'), ('1', 'DEFENSOR LATERAL'), ('2', 'DEFENSOR LIBRE POR BANDA'), ('3', 'DEFENSOR MEDIO CAMPO'), ('4', 'CENTROCAMPISTA DEFENSIVO'), ('5', 'MEDIOCAMPISTA CENTRAL'), ('6', 'MEDIOCAMPISTA EXTERNO'), ('7', 'MEDIOCAMPISTA OFENSIVO'), ('8', 'LATERAL VOLANTE'), ('9', 'VOLANTE DE CONTENCION'), ('10', 'VOLANTE DE CORTE'), ('11', 'VOLANTE DE SALIDA'), ('12', 'VOLANTE EXTERNO'), ('13', 'VOLANTE MIXTO'), ('14', 'VOLANTE DE ENLACE'), ('15', 'VOLANTE DE LLEGADA'), ('16', 'MEDIA PUNTA'), ('17', 'SEGUNDO DELANTERO'), ('18', 'DELANTERO'), ('19', 'PUNTERO'), ('20', 'EXTREMO'), ('21', 'DELANTERO CENTRO')], max_length=2, verbose_name='Position')),
                ('team_number', models.IntegerField(verbose_name='Shirt Number')),
                ('is_starter', models.BooleanField(default=False, verbose_name='Starter')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
