# Generated by Django 4.0.3 on 2022-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Team Name'),
        ),
    ]
